### ISSUE TITLE
Site Titles missing on divisional home pages

### ISSUE THREAD

**Issue by teresasilva71** [ucsc/wcms-design-templates#397]
see https://its-dev.ucsc.edu
https://socsci-dev.ucsc.edu
![site-title missing](https://user-images.githubusercontent.com/7795841/35524699-33962064-04d7-11e8-98c5-ba1553ee2ee2.jpg)
![socsci title](https://user-images.githubusercontent.com/7795841/35524700-33b9da04-04d7-11e8-8e01-85d3632a70a2.jpg)

**Comment by knice** [comment]
This is resolved.

**Comment by teresasilva71** [comment]
Hmmm, this isn't fixed everywhere yet. http://shr-dev.ucsc.edu/

**Comment by knice** [comment]
Because of the original error when I rolled out to WCMS-DEV, all of the division templates need their title blocks re-assigned. [I've fixed this in the Division Home Page template](https://github.com/ucsc/wcms-design-templates/commit/bf47d0b428defa118e0bdb319764d59df8ad4104), so this error will not happen when we rollout to WCMS-STAGE.

So the error is fixed, but it's effects still exist on DEV because the error broke region assignments for the site title.

**Comment by teresasilva71** [comment]
Gotcha. Will this be captured in the dry run rollout on stage?

**Comment by knice** [comment]
Since the bug that caused this is fixed, it won't be a factor in the rollout to stage.

**Comment by knice** [comment]
This issue did not happen in the STAGE roll out (triple-checked this template before I changed it). Closing this ticket.
